### ISSUE TITLE
LCH space and 16-bit to 8-bit match

### ISSUE THREAD

**Issue by whatnick** [mapbox/rio-hist#14]
Here is a basic implementation of matching 16-bit RGB image to an 8-bit target image in LCH space. The image is then saved back in 16-bit RGB with the bit-depth corresponding to that of the sensor and a black point offset to allow further adjustmests without too much clipping of shadows or highlights. The RGB->LCH->RGB transform is lossy in colour for 8-bit outputs, 16-bit preserves the LCH space better and has less quantization. The colour space transfroms are all derived from sckit-image.
```
   from skimage.color import rgb2lab, lab2lch, lch2lab, lab2rgb
    with rasterio.open(test_image) as src:
        rgb_src = src.read()
        profile = src.profile
    
    with rasterio.open(sample_tif) as target:
        rgb_sample = target.read()[:3]
    
    float_rgb_src = rgb_src/(2**16)
    float_rgb_sample = rgb_sample/(2**8)
    rgb_src_image = reshape_as_image(float_rgb_src)
    rgb_sample_image = reshape_as_image(float_rgb_sample)
    
    lch_src = lab2lch(rgb2lab(rgb_src_image))
    lch_sample = lab2lch(rgb2lab(rgb_sample_image))
    
    lch_target = lch_src.copy()
    """Adjust Luminance"""
    lch_target[:,:,0] = hist_match(lch_src[:,:,0],lch_sample[:,:,0])
    """Adjust Chroma"""
    lch_target[:,:,1] = hist_match(lch_src[:,:,1],lch_sample[:,:,1])
    rgb_target_image = lab2rgb(lch2lab(lch_target))
    
    float_rgb_target = reshape_as_raster(rgb_target_image)
    rgb_target = float_rgb_target*(2**bit_depth)+ black_pt
```

**Comment by sgillies** [comment]
Very interesting, but I'm sorry to say we can't implement this.

If anyone wants to submit a PR, let's reopen, but I'm closing this for now.
