### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by geointerest** [mapbox/rio-hist#15]
Ran successfully on your test data 1 but not test data 2 (Andros Island, The Bahamas).  I tried to run on my own satellite imagery and got the same error as test data 2:
AttributeError: "DatasetReader' object has no attribute 'mask flags'.

**Comment by jaredairbusaerial** [comment]
I was able to get data set 2 to work using these commands.
```
rio edit-info --nodata null source2.tif
rio edit-info --nodata null reference2.tif
```

**Comment by tomwang221812** [comment]
I modify utils.py line 17 from:
`if src.mask_flags[0] & MaskFlags.per_dataset:`
to
`if MaskFlags.per_dataset in src.mask_flag_enums[0]:`
and it works on my own datasets now.

Python version : Python 3.6.6 :: Anaconda custom (64-bit)
Rasterio version : 1.0.21
GDAL version : 2.4.0

**Comment by CGPolar** [comment]
@tomwang221812 Your solution solved the issue I had. Thanks a lot !

**Comment by sgillies** [comment]
Closing in favor of #17. No date set yet.
