### ISSUE TITLE
Regarding creation_options

### ISSUE THREAD

**Issue by MostafaOkasha** [mapbox/rio-hist#16]
Beautiful approach to histogram matching by the way!
I am trying to integrate histogram matching into a personal project and am running into an error.
**`from rio_hist.match import hist_match_worker`
`hist_match_worker(mypath, myref, mypath_out, 1,creation_options, '1,2', 'LCH', None)`**
What are the creation_options in this case? Are they used for writing and reading the profiles in rasterio? Are there any options to send to this command to make this work? I tried a similar approach to how you tested the cli but with no success. Thank you!

**Comment by jacquestardie** [comment]
[Creation options](https://github.com/mapbox/rasterio/blob/master/docs/topics/image_options.rst#creation-options) are driver specific (geotiff, jp2, etc) means of affecting/tuning output rasters.

Going to close here - if you have further questions please follow up and include the specific error you're encountering. Thanks!

**Comment by sgillies** [comment]
See also https://rasterio.readthedocs.io/en/stable/topics/image_options.html#creation-options.

**Comment by MostafaOkasha** [comment]
Thank you for the help! This makes so much more sense now.
