### ISSUE TITLE
Non-exact histogram matching

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-hist#8]
"Move the histogram half-way to matching the reference" Useful?

**Comment by dnomadb** [comment]
Also, what about other modes of matching? EG, match only intensity of all channels

**Comment by perrygeo** [comment]
You can currently convert to a different color space and match on a single band. So if Chroma == Saturation == intensity, you could use HSV or LCH color space and match only to the second band. I've tried some variations on that and it works well, changing intensity without really changing the "color".
